spring.datasource.url=jdbc:postgresql://localhost:5432/allanpereiraabrahao_local_db
spring.datasource.username=common_user
spring.datasource.password=common_user
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.web.resources.static-locations=classpath:/static/
server.port=8080

admin.username=admin
admin.password=admin123
